[package]
name = "ecf"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
uuid = { version = "1", features = ["serde", "v4"] }
reed-solomon-erasure = "6.0.0"
